"""tambah kolom 9 perilaku wajib, site control, site suptent

Revision ID: aebb0999049d
Revises: ae3f9b210dee
Create Date: 2025-06-11 22:00:39.545689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebb0999049d'
down_revision = 'ae3f9b210dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perilaku_wajib', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('site_supervisor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('site_supertintendent', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('site_supertintendent')
        batch_op.drop_column('site_supervisor')
        batch_op.drop_column('perilaku_wajib')

    # ### end Alembic commands ###
