"""inital refresh

Revision ID: e76733372972
Revises: 
Create Date: 2026-03-09 21:36:19.330398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76733372972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tofs_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('sub_location', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('clsr_terkait', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('perilaku_wajib', sa.String(length=255), nullable=True),
    sa.Column('site_supervisor', sa.String(length=100), nullable=True),
    sa.Column('site_superintendent', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tofs_report')
    op.drop_table('user')
    # ### end Alembic commands ###
